#! /bin/bash

mkdir .run
RUN_DIR=$(readlink -f .run)
export PYTHONPATH=${RUN_DIR}/lib/python2.7/site-packages
mkdir -p ${PYTHONPATH}
mkdir -p ${RUN_DIR}/www

unzip 3rdparty/jquery.mobile-1.3.0.zip  -d ${RUN_DIR}/www
cp 3rdparty/jquery-1.8.3.min.js ${RUN_DIR}/www
cp 3rdparty/autobahn.min.js ${RUN_DIR}/www

git clone git://github.com/MongoEngine/mongoengine.git .run/me
git --git-dir=.run/me checkout 9f58bc9207a874a91f0165e8ff2f546088097fb2
(cd .run/me ; python setup.py bdist_egg)
cp .run/me/dist/mongoengine-0.7.9-py2.7.egg ${PYTHONPATH}

git clone git://github.com/tavendo/AutobahnPython.git .run/ab
git --git-dir=.run/ab checkout 9e2d2412dbbbba71d1c1bb48327fd7c2078d59b4
make -C .run/ab/autobahn build
cp .run/ab/autobahn/dist/autobahn-0.6.0-py2.7.egg ${PYTHONPATH}

